''' Run analysis.py to generate batchLabel_allData.json, load batchLabel_allData.json, and
    extract params and data
    analysis_temp.py LOADS A SINGLE AMP_CELLNUM COMBINATION FOR NOW
    To do: get epas from all 115 cellnums by using _allData.json file generated by analysis.py
    (once analysis.py is back online)
    
'''
import json
from netpyne import sim, specs

data = json.load(open('test_epas.json'))
e_pas = data['simData']['epas']['cell_0'][1]

# optional ion voltages
#cai = data['simData']['cai_soma']['cell_0'][0]
#cao = data['simData']['cao_soma']['cell_0'][0]
#ik_soma = data['simData']['ik_soma']['cell_0'][0]
ina_soma = data['simData']['ina_soma']['cell_0'][0]

